version: "3.7"
services:
  ## php-fpm
  php-fpm:
    container_name: ${PROJECT_NAME}_php-fpm
    build: ./docker-assets/php-fpm
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: .docker/localdev/php-fpm/scripts
        target: /scripts
        read_only: true
    depends_on:
      - mysql
      - redis
    working_dir: /app
    environment:
      APP_NAME: ${PROJECT_NAME}
      APP_KEY: base64:1PCJD2skvjBXiXwxN7US8DdM3QiSNTuouD7CzSFo0dY=
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 

  # nginx
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    build: ./docker-assets/nginx
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./swagger
        target: /swagger
      - type: bind
        source: ./.docker/localdev/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
    depends_on:
      - php-fpm
    #   - node
    ports:
      - "8080:8080"
      - "443:443"
    working_dir: /app

  # mysql
  mysql:
    container_name: ${PROJECT_NAME}_mysql
    image: mysql
    volumes:
      - type: bind
        source: ./.docker/localdev/mysql/custom.cnf
        target: /etc/mysql/conf.d/custom.cnf
        read_only: true
      - type: bind
        source: ./.mysql_data
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret

  ## redis
  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:alpine

#   ## node
#   node:
#     container_name: ${PROJECT_NAME}_node
#     image: node
#     volumes:
#       - type: bind
#         source: ./node
#         target: /app
#       - type: bind
#         source: .docker/localdev/node/scripts
#         target: /scripts
#         read_only: true
#     depends_on:
#       - mysql
#     working_dir: /app
#     entrypoint: /scripts/bootstrap.sh
